version: "3"

silent: true

tasks:
  default:
    desc: list tasks
    cmd: |
      task --list-all

  tidy:
    desc: tidy dependencies
    cmd: |
      go mod tidy

  test:
    desc: unit testing
    deps:
      - tidy
    cmd: |
      DEBUG=1 go test -race -count=1 -cover -timeout=60s {{.CLI_ARGS}}
